apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kaas-api.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  # autoScaling:
  #   horizontal:
  #     maxReplicas: {{ .Values.autoScaling.maxReplicas }}
  #     averageCPU: {{ .Values.autoScaling.averageCpu }}
  #     averageRelativeMemory: {{ .Values.autoScaling.averageRelativeMemory }}
  selector:
    matchLabels:
      app: {{ include "kaas-api.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "kaas-api.name" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}
        ports:
        - containerPort: {{ .Values.image.port }}
        args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 60
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 60
          periodSeconds: 5
      

  
